# Generated by Django 5.1.3 on 2025-03-19 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('FACTURA_A', 'Factura A'), ('FACTURA_B', 'Factura B'), ('TICKET', 'Ticket'), ('NC', 'Nota de Crédito')], max_length=50)),
                ('numero_comprobante', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cuit_emisor', models.CharField(max_length=11)),
                ('nombre_emisor', models.CharField(max_length=255)),
                ('cuit_receptor', models.CharField(blank=True, max_length=11, null=True)),
                ('nombre_receptor', models.CharField(blank=True, max_length=255, null=True)),
                ('condicion_iva', models.CharField(max_length=50)),
                ('condicion_venta', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moneda', models.CharField(default='ARS', max_length=10)),
                ('cae', models.CharField(blank=True, max_length=14, null=True)),
                ('fecha_vencimiento_cae', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('iva', models.DecimalField(decimal_places=2, default=21.0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comprobantes.comprobante')),
            ],
        ),
    ]
