# Generated by Django 5.1.3 on 2025-03-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='tipo_comprobante',
            field=models.CharField(max_length=50),
        ),
    ]
